from typing import Protocol
class Evaluator(Protocol):
 def prepare(self): ...
 def compile(self): ...
 def check_correctness(self): ...
 def benchmark(self): ...
 def profile(self): ...
 def static_evidence(self): ...
 def cleanup(self): ...
