"""Metadata-only import from existing aka-local records and known remote canonical records."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; AKA=ROOT.parent
def write(p,x): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def rec(i,title,op,plat,back,dec,src,level,summary,mechanisms=()):
 return {'schema_version':1,'id':i,'title':title,'timestamp':'UNKNOWN','operator':op,'hardware':plat,'architecture':'sm_120' if plat=='rtx5060_laptop_sm120' else ('BI-V150' if plat=='biv150_corex' else 'UNKNOWN'),'backend':back,'framework':back,'dtype':[],'mode':'training','scope':{},'shape_regime':{},'baseline':{},'candidate':{},'hypothesis':'','mechanisms':list(mechanisms),'changes':[],'evidence':{'summary':summary},'performance':{'summary':summary},'decision':dec,'failure_class':None,'observations':[summary],'failed_assumptions':[],'unresolved_questions':[],'next_directions':[],'provenance':{'source_type':src[0],'source_path':src[1],'source_commit':None,'canonical':src[0] in ('LEGACY_AKA_LOCAL','REMOTE_ATREX_CANONICAL'),'evidence_level':level,'location':'remote_biv150' if src[0].startswith('REMOTE') else 'local','read_only':src[0].startswith('REMOTE')},'tags':['imported']}
def main():
 rows=[rec('aka-rmsnorm-v0','Standalone RMSNorm V0 eager reference','rms_norm_train','rtx5060_laptop_sm120','pytorch_eager','BASELINE',('LEGACY_AKA_LOCAL',str(AKA/'campaigns/rms_norm/backward/episode_1/decision.json')),2,'Official eager reference used as correctness oracle and initial performance baseline',[]),rec('aka-rmsnorm-v1','Standalone RMSNorm V1 fused row reduction','rms_norm_train','rtx5060_laptop_sm120','cuda_cpp','PROMOTE',('LEGACY_AKA_LOCAL',str(AKA/'campaigns/rms_norm/backward/episode_1/decision.json')),3,'56/56 correctness PASS; arithmetic mean speedup 7.202740x vs eager; one block per row, shared-memory tree reduction',['fused_row_reduction','shared_memory_reduction']),rec('aka-rmsnorm-v2','Standalone RMSNorm V2 warp reduction','rms_norm_train','rtx5060_laptop_sm120','cuda_cpp','ACCEPT',('LEGACY_AKA_LOCAL',str(AKA/'campaigns/rms_norm/episode_2/decision.json')),3,'56/56 correctness PASS; repeated ABBA arithmetic mean ~1.074x; 50/56 winning shape means; shared memory 2048B to 1056B',['warp_reduction']),rec('aka-swiglu-v2b','Standalone SwiGLU V2b','swiglu','rtx5060_laptop_sm120','cuda_cpp','ACCEPT',('LEGACY_AKA_LOCAL',str(AKA/'STATUS.md')),3,'RTX5060 ABBA: M256 1.582x, M1024 1.506x, M4096 1.673x',['fusion','half2']),rec('aka-swiglu-v3','Standalone SwiGLU V3 robustness','swiglu','rtx5060_laptop_sm120','cuda_cpp','REJECT',('LEGACY_AKA_LOCAL',str(AKA/'campaigns/luna/episode_3/robustness_abba.json')),3,'robustness arithmetic aggregate 0.986540x; KEEP_V2B',['candidate comparison'])]
 rows += [rec('remote-residual-v5','Residual RMSNorm flat row-batched','residual_rmsnorm_train','biv150_corex','corex_triton','ACCEPT',('REMOTE_ATREX_CANONICAL','/private/atrex-megatron/campaigns/kernel_opt_residual_rmsnorm_train_triton_bi_v150_production/memory/v5.json'),3,'5 hidden workloads pass; 5-seed all-pass; score 19.75/19.81 vs V3 12.72; ~56 percent',['row_batching','shape_dispatch']),rec('remote-swiglu-v6','Bias SwiGLU direct2 regime','bias_swiglu_train','biv150_corex','corex_triton','ACCEPT',('REMOTE_ATREX_CANONICAL','/private/atrex-megatron/campaigns/kernel_opt_bias_swiglu_train_triton_bi_v150_production/memory/v6.json'),3,'5-seed all-pass; score 2.940293; authoritative improvement 4.016 percent',['shape_dispatch','launch_reduction']),rec('remote-moe-v0','MoE Grouped MLP reference baseline','moe_grouped_mlp_train','biv150_corex','corex_triton','BASELINE',('REMOTE_ATREX_CANONICAL','/private/atrex-megatron/campaigns/kernel_opt_moe_grouped_mlp_train_triton_bi_v150_production/memory/v0.json'),2,'11 shapes; correctness PASS',[]),rec('remote-moe-v1','MoE Grouped MLP Triton attempt','moe_grouped_mlp_train','biv150_corex','corex_triton','REJECT',('REMOTE_ATREX_CANONICAL','/private/atrex-megatron/campaigns/kernel_opt_moe_grouped_mlp_train_triton_bi_v150_production/memory/v1.json'),2,'correctness FAIL; campaign blocked',['triton'])]
 for r in rows: write(ROOT/'experiments'/r['operator']/r['hardware']/r['id']/'record.json',r)
 print('imported',len(rows))
if __name__=='__main__': main()
