import base64,json,paramiko
from pathlib import Path
root=Path(__file__).resolve().parents[2];secret=__import__('os').environ['AKA_V100_PASSWORD'];s=paramiko.SSHClient();s.set_missing_host_key_policy(paramiko.AutoAddPolicy());s.connect('<REMOTE_HOST>',username='<REMOTE_USER>',password=secret,timeout=20)
code='import argparse,json,statistics,torch,torch.distributed as dist; from megatron.core import parallel_state; from megatron.core.process_groups_config import ProcessGroupCollection; from megatron.core.tensor_parallel.random import get_cuda_rng_tracker; from megatron.core.transformer.transformer_config import TransformerConfig; from megatron.core.transformer.dot_product_attention import DotProductAttention; from megatron.core.transformer.enums import AttnMaskType; p=argparse.ArgumentParser(); p.add_argument("--S",type=int,default=16); p.add_argument("--B",type=int,default=1); p.add_argument("--mode",default="correctness"); a=p.parse_args(); dist.init_process_group("gloo",init_method="tcp://127.0.0.1:29594",rank=0,world_size=1); parallel_state._set_global_memory_buffer(); get_cuda_rng_tracker().add("model-parallel-rng",1234); pg=ProcessGroupCollection(); pg.tp=dist.group.WORLD; cfg=TransformerConfig(num_layers=1,hidden_size=1024,num_attention_heads=16,num_query_groups=16,kv_channels=64,attention_dropout=0.0,attention_softmax_in_fp32=True,masked_softmax_fusion=False,fp16=True,params_dtype=torch.float16); m=DotProductAttention(cfg,1,AttnMaskType.no_mask,"self",pg_collection=pg); S,B,H,D=a.S,a.B,16,64; torch.manual_seed(1717); q=torch.randn(S,B,H,D,device="cuda",dtype=torch.float16,requires_grad=True); k=torch.randn_like(q,requires_grad=True); v=torch.randn_like(q,requires_grad=True); y=m(q,k,v,None); q0=q.detach().permute(1,2,0,3).float().reshape(B*H,S,D); k0=k.detach().permute(1,2,0,3).float().reshape(B*H,S,D); v0=v.detach().permute(1,2,0,3).float().reshape(B*H,S,D); o=torch.bmm(torch.softmax(torch.bmm(q0,k0.transpose(1,2))*.125,dim=-1),v0).reshape(B,H,S,D).permute(2,0,1,3).reshape(S,B,1024).half(); d=(y.float()-o.float()).abs(); g=torch.randn_like(y); y.backward(g,retain_graph=True); xq=q.detach().float().requires_grad_(); xk=k.detach().float().requires_grad_(); xv=v.detach().float().requires_grad_(); xq0=xq.permute(1,2,0,3).reshape(B*H,S,D); xk0=xk.permute(1,2,0,3).reshape(B*H,S,D); xv0=xv.permute(1,2,0,3).reshape(B*H,S,D); oo=torch.bmm(torch.softmax(torch.bmm(xq0,xk0.transpose(1,2))*.125,dim=-1),xv0).reshape(B,H,S,D).permute(2,0,1,3).reshape(S,B,1024); oo.backward(g.float()); gr=[float((aa.float()-bb.float()).abs().max()) for aa,bb in [(q.grad,xq.grad),(k.grad,xk.grad),(v.grad,xv.grad)]]; out={"module":type(m).__name__,"scale":m.softmax_scale,"q_shape":[S,B,H,D],"q_stride":list(q.stride()),"output_shape":list(y.shape),"output_dtype":str(y.dtype),"forward_max_abs":float(d.max()),"forward_max_rel":float((d/o.float().abs().clamp_min(1e-12)).max()),"dQ_dK_dV_max_abs":gr,"mask":"no_mask/dense","dropout":0.0,"collectives":0}; print(json.dumps(out)); dist.destroy_process_group()'
payload=base64.b64encode(code.encode()).decode();s.exec_command('echo '+payload+' | base64 -d > /tmp/aka_phase17a_replay.py')[1].read()
outs=[]
for S,B in [(16,1),(64,2),(128,2)]:
 cmd=f'cd ~/aka_targets/megatron-lm-5be9626 && PYTHONPATH=$PWD <REMOTE_HOME>/venvs/lerobot-act/bin/python /tmp/aka_phase17a_replay.py --S {S} --B {B}';_,o,e=s.exec_command(cmd,timeout=600);outs.append({'shape':[S,B,1024],'stdout':o.read().decode(),'stderr':e.read().decode()[-1000:]})
(root/'targets/megatron_5be9626/attention_phase17a_replay_raw.json').write_text(json.dumps(outs,indent=2)+'\n');print(json.dumps(outs,indent=2));s.close()
